#!/usr/bin/env python3
"""Convert the repo RSA YAML keypair into an armored OpenPGP public key."""

from __future__ import annotations

import argparse
import base64
import hashlib
import struct
import sys
import time
from pathlib import Path

import yaml
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

CRC24_INIT = 0xB704CE
CRC24_POLY = 0x1864CFB
RSA_GENERAL_ALGO = 0x01
SHA256_ALGO = 0x08
POSITIVE_CERTIFICATION = 0x13


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an ASCII-armored OpenPGP public key from RSA YAML inputs."
    )
    parser.add_argument("--private-key", required=True, help="Path to rsa-private-key-v1 YAML")
    parser.add_argument("--public-key", required=True, help="Path to rsa-public-key-v1 YAML")
    parser.add_argument("--name", required=True, help="User ID display name")
    parser.add_argument("--email", required=True, help="User ID email address")
    parser.add_argument("--output", required=True, help="ASCII-armored OpenPGP public key output")
    parser.add_argument(
        "--created-unix",
        type=int,
        default=int(time.time()),
        help="Unix timestamp to embed in the OpenPGP key material",
    )
    return parser.parse_args()


def load_yaml_document(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        document = yaml.safe_load(handle)
    if not isinstance(document, dict):
        raise ValueError(f"{path} did not contain a YAML mapping")
    return document


def encode_mpi(value: int) -> bytes:
    bit_length = value.bit_length()
    octets = value.to_bytes((bit_length + 7) // 8, "big")
    return struct.pack(">H", bit_length) + octets


def encode_length(length: int) -> bytes:
    if length < 192:
        return bytes([length])
    if length < 8384:
        adjusted = length - 192
        return bytes([(adjusted >> 8) + 192, adjusted & 0xFF])
    return b"\xFF" + struct.pack(">I", length)


def encode_packet(tag: int, body: bytes) -> bytes:
    return bytes([0xC0 | tag]) + encode_length(len(body)) + body


def encode_subpacket(subpacket_type: int, data: bytes, critical: bool = False) -> bytes:
    tag = subpacket_type | (0x80 if critical else 0)
    body = bytes([tag]) + data
    return encode_length(len(body)) + body


def compute_crc24(payload: bytes) -> int:
    crc = CRC24_INIT
    for octet in payload:
        crc ^= octet << 16
        for _ in range(8):
            crc <<= 1
            if crc & 0x1000000:
                crc ^= CRC24_POLY
    return crc & 0xFFFFFF


def armor_public_key(payload: bytes) -> str:
    encoded = base64.b64encode(payload).decode("ascii")
    crc = base64.b64encode(compute_crc24(payload).to_bytes(3, "big")).decode("ascii")
    lines = [encoded[index : index + 64] for index in range(0, len(encoded), 64)]
    return (
        "-----BEGIN PGP PUBLIC KEY BLOCK-----\n"
        "Comment: Generated by convert_rsa_yaml_to_pgp.py\n"
        "\n"
        + "\n".join(lines)
        + f"\n={crc}\n-----END PGP PUBLIC KEY BLOCK-----\n"
    )


def build_private_key(document: dict) -> rsa.RSAPrivateKey:
    if document.get("format") != "rsa-private-key-v1":
        raise ValueError("private key YAML must use format rsa-private-key-v1")

    public_exponent = int(document["public_exponent"])
    private_exponent = int(document["private_exponent"])
    modulus = int(document["modulus"])
    prime_p = int(document["primes"]["p"])
    prime_q = int(document["primes"]["q"])

    if prime_p * prime_q != modulus:
        raise ValueError("private key primes do not multiply to the advertised modulus")

    numbers = rsa.RSAPrivateNumbers(
        p=prime_p,
        q=prime_q,
        d=private_exponent,
        dmp1=rsa.rsa_crt_dmp1(private_exponent, prime_p),
        dmq1=rsa.rsa_crt_dmq1(private_exponent, prime_q),
        iqmp=rsa.rsa_crt_iqmp(prime_p, prime_q),
        public_numbers=rsa.RSAPublicNumbers(public_exponent, modulus),
    )
    return numbers.private_key()


def validate_public_key(document: dict, private_key: rsa.RSAPrivateKey) -> rsa.RSAPublicKey:
    if document.get("format") != "rsa-public-key-v1":
        raise ValueError("public key YAML must use format rsa-public-key-v1")

    public_exponent = int(document["public_exponent"])
    modulus = int(document["modulus"])
    public_key = rsa.RSAPublicNumbers(public_exponent, modulus).public_key()

    private_public = private_key.public_key().public_numbers()
    public_numbers = public_key.public_numbers()
    if (
        private_public.e != public_numbers.e
        or private_public.n != public_numbers.n
    ):
        raise ValueError("public key YAML does not match the supplied private key")

    return public_key


def build_public_key_packet_body(
    public_key: rsa.RSAPublicKey, created_unix: int
) -> bytes:
    numbers = public_key.public_numbers()
    return (
        b"\x04"
        + struct.pack(">I", created_unix)
        + bytes([RSA_GENERAL_ALGO])
        + encode_mpi(numbers.n)
        + encode_mpi(numbers.e)
    )


def build_user_id(name: str, email: str) -> bytes:
    return f"{name} <{email}>".encode("utf-8")


def build_self_signature(
    private_key: rsa.RSAPrivateKey,
    public_key_packet_body: bytes,
    user_id: bytes,
    created_unix: int,
) -> bytes:
    fingerprint_source = (
        b"\x99"
        + struct.pack(">H", len(public_key_packet_body))
        + public_key_packet_body
    )
    user_id_source = b"\xB4" + struct.pack(">I", len(user_id)) + user_id
    fingerprint = hashlib.sha1(fingerprint_source).digest()
    key_id = fingerprint[-8:]

    hashed_subpackets = b"".join(
        [
            encode_subpacket(2, struct.pack(">I", created_unix)),
            encode_subpacket(27, b"\x0D"),
            encode_subpacket(11, bytes([9, 8, 7])),
            encode_subpacket(21, bytes([10, 9, 8, 2])),
            encode_subpacket(22, bytes([2, 1, 0])),
            encode_subpacket(25, b"\x01"),
            encode_subpacket(30, b"\x01"),
            encode_subpacket(33, b"\x04" + fingerprint),
        ]
    )
    unhashed_subpackets = encode_subpacket(16, key_id)

    signature_head = (
        b"\x04"
        + bytes([POSITIVE_CERTIFICATION, RSA_GENERAL_ALGO, SHA256_ALGO])
        + struct.pack(">H", len(hashed_subpackets))
        + hashed_subpackets
    )
    trailer = b"\x04\xFF" + struct.pack(">I", len(signature_head))
    signed_data = fingerprint_source + user_id_source + signature_head + trailer

    left_hash = hashlib.sha256(signed_data).digest()[:2]
    signature_bytes = private_key.sign(
        signed_data,
        padding.PKCS1v15(),
        hashes.SHA256(),
    )
    signature_mpi = encode_mpi(int.from_bytes(signature_bytes, "big"))

    return (
        signature_head
        + struct.pack(">H", len(unhashed_subpackets))
        + unhashed_subpackets
        + left_hash
        + signature_mpi
    )


def main() -> int:
    args = parse_args()
    private_path = Path(args.private_key)
    public_path = Path(args.public_key)
    output_path = Path(args.output)

    private_document = load_yaml_document(private_path)
    public_document = load_yaml_document(public_path)
    private_key = build_private_key(private_document)
    public_key = validate_public_key(public_document, private_key)

    public_key_packet_body = build_public_key_packet_body(public_key, args.created_unix)
    user_id = build_user_id(args.name, args.email)
    signature_body = build_self_signature(
        private_key, public_key_packet_body, user_id, args.created_unix
    )

    armored = armor_public_key(
        encode_packet(6, public_key_packet_body)
        + encode_packet(13, user_id)
        + encode_packet(2, signature_body)
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(armored, encoding="utf-8")

    print(
        f"Wrote OpenPGP public key {output_path} for {args.email}",
        file=sys.stdout,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
