#!/usr/bin/env python3
"""Build a bash grid-search runner for the small-batch beam workflow."""

from __future__ import annotations

import argparse
import itertools
import json
import shlex
import stat
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

JsonValue = bool | int | float | str | None | list["JsonValue"] | dict[str, "JsonValue"]


@dataclass(frozen=True)
class ReplacementSpec:
    """Describe one jq field replacement and the values it should sweep."""

    name: str
    path: str
    values: tuple[JsonValue, ...]


def replace(path: str, values: Sequence[JsonValue], *, name: str | None = None) -> ReplacementSpec:
    """Return a replacement schedule for one jq field path."""

    if not path.startswith("."):
        raise ValueError(f"jq path must start with '.', got {path!r}")

    rendered_values = tuple(values)
    if not rendered_values:
        raise ValueError(f"replacement for {path!r} must include at least one value")

    return ReplacementSpec(
        name=name or path.lstrip(".").replace(".", "_"),
        path=path,
        values=rendered_values,
    )


# Edit this schedule in code, then rerun this builder to regenerate the bash runner.
GRID_SCHEDULE: tuple[ReplacementSpec, ...] = (
    replace(
        ".engine.avalanche_combination_recursive_resample_count",
        [[10_000], [100_000], [10_000_000]],
        name="recursive_resample_count",
    ),
    # Example:
    # replace(".engine.avalanche_combination_samples", [100_000, 500_000], name="sample_count"),
)


def build_grid_plan(schedule: Sequence[ReplacementSpec]) -> list[dict[str, object]]:
    """Expand the schedule into a concrete cartesian-product grid plan."""

    if not schedule:
        raise ValueError("GRID_SCHEDULE must contain at least one replacement")

    plan: list[dict[str, object]] = []
    value_product = itertools.product(*(spec.values for spec in schedule))
    for index, value_tuple in enumerate(value_product, start=1):
        changes = []
        summary_parts = []
        for spec, value in zip(schedule, value_tuple, strict=True):
            changes.append({"name": spec.name, "path": spec.path, "value": value})
            summary_parts.append(f"{spec.name}={json.dumps(value, separators=(',', ':'))}")

        plan.append(
            {
                "index": index,
                "summary": ", ".join(summary_parts),
                "changes": changes,
            }
        )

    return plan


def render_script(source_config: str, destination_script: str, plan: Sequence[dict[str, object]]) -> str:
    """Render the generated bash script."""

    plan_json = json.dumps(plan, indent=2, sort_keys=False)
    source_default = shlex.quote(source_config)
    destination_default = shlex.quote(destination_script)

    return textwrap.dedent(
        f"""\
#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/grid_search_builder.py.
# Edit GRID_SCHEDULE in that builder, then regenerate this file.

SOURCE_CONFIG_DEFAULT={source_default}
DEST_SCRIPT_DEFAULT={destination_default}
RUNNER_SCRIPT_DEFAULT='scripts/run_small_batch_beam.sh'
GRID_ROOT_DEFAULT='./grid'

SOURCE_CONFIG="${{SOURCE_CONFIG:-$SOURCE_CONFIG_DEFAULT}}"
DEST_SCRIPT="${{DEST_SCRIPT:-$DEST_SCRIPT_DEFAULT}}"
RUNNER_SCRIPT="${{RUNNER_SCRIPT:-$RUNNER_SCRIPT_DEFAULT}}"
GRID_ROOT="${{GRID_ROOT:-$GRID_ROOT_DEFAULT}}"
STATIC_CONFIG="${{STATIC_CONFIG:-${{GRID_ROOT}}/base_config.json}}"
RUNS_PER_ITERATION="${{RUNS_PER_ITERATION:-1}}"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required but was not found in PATH." >&2
  exit 1
fi

if [[ ! -f "${{SOURCE_CONFIG}}" ]]; then
  echo "Missing source config ${{SOURCE_CONFIG}}" >&2
  exit 1
fi

if [[ ! -f "${{RUNNER_SCRIPT}}" ]]; then
  echo "Missing runner script ${{RUNNER_SCRIPT}}" >&2
  exit 1
fi

if [[ "${{RUNS_PER_ITERATION}}" != "1" ]]; then
  echo "RUNS_PER_ITERATION must be 1 so each grid iteration maps to grid/<n>/session.json." >&2
  exit 1
fi

GRID_PLAN_JSON=$(cat <<'JSON'
{plan_json}
JSON
)

sanitize_source_config() {{
  mkdir -p "${{GRID_ROOT}}"
  sed -E 's,//.*$,,' "${{SOURCE_CONFIG}}" | jq '.' > "${{STATIC_CONFIG}}.tmp"
  mv "${{STATIC_CONFIG}}.tmp" "${{STATIC_CONFIG}}"
}}

apply_json_change() {{
  local target_config=$1
  local jq_path=$2
  local jq_value=$3

  jq --argjson value "${{jq_value}}" "${{jq_path}} = \\$value" "${{target_config}}" > "${{target_config}}.tmp"
  mv "${{target_config}}.tmp" "${{target_config}}"
}}

log_line() {{
  local log_file=$1
  local message=$2
  printf '%s\\n' "${{message}}" | tee -a "${{log_file}}"
}}

total_iterations=$(jq 'length' <<< "${{GRID_PLAN_JSON}}")
sanitize_source_config

echo "Generated script: ${{DEST_SCRIPT}}"
echo "Grid root: ${{GRID_ROOT}}"
echo "Static config: ${{STATIC_CONFIG}}"
echo "Source config: ${{SOURCE_CONFIG}}"
echo "Small-batch beam runner: ${{RUNNER_SCRIPT}}"
echo "Grid iterations: ${{total_iterations}}"

for iteration in $(seq 1 "${{total_iterations}}"); do
  iteration_json=$(jq -c ".[$((iteration - 1))]" <<< "${{GRID_PLAN_JSON}}")
  iteration_summary=$(jq -r '.summary' <<< "${{iteration_json}}")
  iteration_dir="${{GRID_ROOT}}/${{iteration}}"
  iteration_config="${{iteration_dir}}/config.json"
  iteration_session="${{iteration_dir}}/session.json"
  iteration_log="${{iteration_dir}}/current.log"
  iteration_script_log="${{iteration_dir}}/current_script.log"

  mkdir -p "${{iteration_dir}}"
  cp "${{STATIC_CONFIG}}" "${{iteration_config}}"
  : > "${{iteration_log}}"
  : > "${{iteration_script_log}}"

  log_line "${{iteration_script_log}}" ""
  log_line "${{iteration_script_log}}" "===== GRID ITERATION ${{iteration}}/${{total_iterations}} ====="
  log_line "${{iteration_script_log}}" "Summary: ${{iteration_summary}}"
  log_line "${{iteration_script_log}}" "Iteration config: ${{iteration_config}}"
  log_line "${{iteration_script_log}}" "Session path: ${{iteration_session}}"
  while IFS= read -r change_json; do
    change_name=$(jq -r '.name' <<< "${{change_json}}")
    change_path=$(jq -r '.path' <<< "${{change_json}}")
    change_value=$(jq -c '.value' <<< "${{change_json}}")
    apply_json_change "${{iteration_config}}" "${{change_path}}" "${{change_value}}"
    log_line "${{iteration_script_log}}" "Change: ${{change_name}} (${{change_path}} = ${{change_value}})"
  done < <(jq -c '.changes[]' <<< "${{iteration_json}}")

  log_line "${{iteration_script_log}}" "Launching ${{RUNNER_SCRIPT}}"
  CONFIG="${{iteration_config}}" \\
  ANALYSIS_LOG="${{iteration_log}}" \\
  SCRIPT_LOG="${{iteration_script_log}}" \\
  LOG_DIR="${{iteration_dir}}" \\
  RUNS="${{RUNS_PER_ITERATION}}" \\
  RESUME=1 \\
  SESSION_JSON_PATH="${{iteration_session}}" \\
  bash "${{RUNNER_SCRIPT}}"
done
"""
    )


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for the builder."""

    parser = argparse.ArgumentParser(
        description="Generate a bash grid-search runner for the small-batch beam workflow.",
    )
    parser.add_argument("source_config", help="Path to the source config JSON/JSONC file.")
    parser.add_argument("destination_script", help="Path to the generated bash script.")
    return parser.parse_args()


def main() -> int:
    """Build the grid-search bash script on disk."""

    args = parse_args()
    source_config = Path(args.source_config)
    if not source_config.is_file():
        raise SystemExit(f"Missing source config: {source_config}")

    destination_script = Path(args.destination_script)
    plan = build_grid_plan(GRID_SCHEDULE)
    rendered = render_script(args.source_config, args.destination_script, plan)

    destination_script.parent.mkdir(parents=True, exist_ok=True)
    destination_script.write_text(rendered, encoding="utf-8")

    current_mode = destination_script.stat().st_mode
    destination_script.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Wrote {destination_script} with {len(plan)} grid iterations.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
