#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/grid_search_builder.py.
# Edit GRID_SCHEDULE in that builder, then regenerate this file.

SOURCE_CONFIG_DEFAULT=config/rsa_config_small_batch.json
DEST_SCRIPT_DEFAULT=scripts/run_grid_search.sh
RUNNER_SCRIPT_DEFAULT='scripts/run_small_batch_beam.sh'
GRID_ROOT_DEFAULT='./grid'

SOURCE_CONFIG="${SOURCE_CONFIG:-$SOURCE_CONFIG_DEFAULT}"
DEST_SCRIPT="${DEST_SCRIPT:-$DEST_SCRIPT_DEFAULT}"
RUNNER_SCRIPT="${RUNNER_SCRIPT:-$RUNNER_SCRIPT_DEFAULT}"
GRID_ROOT="${GRID_ROOT:-$GRID_ROOT_DEFAULT}"
STATIC_CONFIG="${STATIC_CONFIG:-${GRID_ROOT}/base_config.json}"
RUNS_PER_ITERATION="${RUNS_PER_ITERATION:-1}"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required but was not found in PATH." >&2
  exit 1
fi

if [[ ! -f "${SOURCE_CONFIG}" ]]; then
  echo "Missing source config ${SOURCE_CONFIG}" >&2
  exit 1
fi

if [[ ! -f "${RUNNER_SCRIPT}" ]]; then
  echo "Missing runner script ${RUNNER_SCRIPT}" >&2
  exit 1
fi

if [[ "${RUNS_PER_ITERATION}" != "1" ]]; then
  echo "RUNS_PER_ITERATION must be 1 so each grid iteration maps to grid/<n>/session.json." >&2
  exit 1
fi

GRID_PLAN_JSON=$(cat <<'JSON'
[
  {
    "index": 1,
    "summary": "recursive_resample_count=10000",
    "changes": [
      {
        "name": "recursive_resample_count",
        "path": ".engine.avalanche_combination_recursive_resample_count",
        "value": 10000
      }
    ]
  },
  {
    "index": 2,
    "summary": "recursive_resample_count=100000",
    "changes": [
      {
        "name": "recursive_resample_count",
        "path": ".engine.avalanche_combination_recursive_resample_count",
        "value": 100000
      }
    ]
  },
  {
    "index": 3,
    "summary": "recursive_resample_count=10000000",
    "changes": [
      {
        "name": "recursive_resample_count",
        "path": ".engine.avalanche_combination_recursive_resample_count",
        "value": 10000000
      }
    ]
  }
]
JSON
)

sanitize_source_config() {
  mkdir -p "${GRID_ROOT}"
  sed -E 's,//.*$,,' "${SOURCE_CONFIG}" | jq '.' > "${STATIC_CONFIG}.tmp"
  mv "${STATIC_CONFIG}.tmp" "${STATIC_CONFIG}"
}

apply_json_change() {
  local target_config=$1
  local jq_path=$2
  local jq_value=$3

  jq --argjson value "${jq_value}" "${jq_path} = \$value" "${target_config}" > "${target_config}.tmp"
  mv "${target_config}.tmp" "${target_config}"
}

log_line() {
  local log_file=$1
  local message=$2
  printf '%s\n' "${message}" | tee -a "${log_file}"
}

total_iterations=$(jq 'length' <<< "${GRID_PLAN_JSON}")
sanitize_source_config

echo "Generated script: ${DEST_SCRIPT}"
echo "Grid root: ${GRID_ROOT}"
echo "Static config: ${STATIC_CONFIG}"
echo "Source config: ${SOURCE_CONFIG}"
echo "Small-batch beam runner: ${RUNNER_SCRIPT}"
echo "Grid iterations: ${total_iterations}"

for iteration in $(seq 1 "${total_iterations}"); do
  iteration_json=$(jq -c ".[$((iteration - 1))]" <<< "${GRID_PLAN_JSON}")
  iteration_summary=$(jq -r '.summary' <<< "${iteration_json}")
  iteration_dir="${GRID_ROOT}/${iteration}"
  iteration_config="${iteration_dir}/config.json"
  iteration_session="${iteration_dir}/session.json"
  iteration_log="${iteration_dir}/current.log"
  iteration_script_log="${iteration_dir}/current_script.log"

  mkdir -p "${iteration_dir}"
  cp "${STATIC_CONFIG}" "${iteration_config}"
  : > "${iteration_log}"
  : > "${iteration_script_log}"

  log_line "${iteration_script_log}" ""
  log_line "${iteration_script_log}" "===== GRID ITERATION ${iteration}/${total_iterations} ====="
  log_line "${iteration_script_log}" "Summary: ${iteration_summary}"
  log_line "${iteration_script_log}" "Iteration config: ${iteration_config}"
  log_line "${iteration_script_log}" "Session path: ${iteration_session}"
  while IFS= read -r change_json; do
    change_name=$(jq -r '.name' <<< "${change_json}")
    change_path=$(jq -r '.path' <<< "${change_json}")
    change_value=$(jq -c '.value' <<< "${change_json}")
    apply_json_change "${iteration_config}" "${change_path}" "${change_value}"
    log_line "${iteration_script_log}" "Change: ${change_name} (${change_path} = ${change_value})"
  done < <(jq -c '.changes[]' <<< "${iteration_json}")

  log_line "${iteration_script_log}" "Launching ${RUNNER_SCRIPT}"
  CONFIG="${iteration_config}" \
  ANALYSIS_LOG="${iteration_log}" \
  SCRIPT_LOG="${iteration_script_log}" \
  LOG_DIR="${iteration_dir}" \
  RUNS="${RUNS_PER_ITERATION}" \
  RESUME=1 \
  SESSION_JSON_PATH="${iteration_session}" \
  bash "${RUNNER_SCRIPT}"
done
