use rand::SeedableRng;
use rand::rngs::StdRng;
use rand::seq::SliceRandom;

use crate::windows::WindowPartitionSet;

/// Errors returned by the bitflow generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BitflowError {
    InvalidBitWidth,
    InvalidPartitionRange,
    InvalidIterations,
    InvalidTrials,
    InvalidFlipCount,
    InvalidPowModulus,
    MessageBitWidthMismatch,
}

impl std::fmt::Display for BitflowError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BitflowError::InvalidBitWidth => write!(f, "bit width must be non-zero"),
            BitflowError::InvalidPartitionRange => {
                write!(f, "partition sizes must be within the bit width")
            }
            BitflowError::InvalidIterations => write!(f, "iteration count must be non-zero"),
            BitflowError::InvalidTrials => write!(f, "trial count must be non-zero"),
            BitflowError::InvalidFlipCount => {
                write!(f, "max partitions to flip must be non-zero")
            }
            BitflowError::InvalidPowModulus => {
                write!(f, "pow-mod modulus must be non-zero")
            }
            BitflowError::MessageBitWidthMismatch => {
                write!(f, "message bit width does not match config")
            }
        }
    }
}

impl std::error::Error for BitflowError {}

/// Progression model for partition sizes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PartitionProgression {
    /// Keep a fixed partition size for every iteration.
    Fixed { size: usize },
    /// Increase partition size linearly each iteration.
    Linear { start: usize, step: usize },
    /// Increase partition size geometrically each iteration.
    Geometric { start: usize, factor: usize },
    /// Use a repeating sequence of explicit partition sizes.
    Sequence { sizes: Vec<usize> },
}

/// Configuration for generating bitflow candidates.
#[derive(Debug, Clone)]
pub struct BitflowConfig {
    pub bit_width: usize,
    pub min_partition_size: usize,
    pub max_partition_size: usize,
    pub progression: PartitionProgression,
    pub max_iterations: usize,
    pub max_partitions_to_flip: usize,
    pub per_candidate_trials: usize,
    pub seed: u64,
    pub pow_mod_base: u64,
    pub pow_mod_modulus: u64,
}

/// Represents a contiguous bit partition.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BitPartition {
    pub start: usize,
    pub end: usize,
}

impl BitPartition {
    /// Returns the length of the partition.
    ///
    /// # Parameters
    /// - None.
    ///
    /// # Returns
    /// - `usize`: Number of bits in the partition.
    ///
    /// # Expected Output
    /// - Returns the partition length; no side effects.
    pub fn len(&self) -> usize {
        self.end.saturating_sub(self.start)
    }
}

/// Candidate generated by bitflow with inversion metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BitflowCandidate {
    pub iteration: usize,
    pub trial: usize,
    pub partition_size: usize,
    pub inverted_partitions: Vec<usize>,
    pub bits: Vec<bool>,
}

/// Generator for partitioned, inverted bitflow candidates.
#[derive(Debug)]
pub struct BitflowEngine {
    config: BitflowConfig,
    rng: StdRng,
}

impl BitflowEngine {
    /// Creates a bitflow engine with the provided configuration.
    ///
    /// # Parameters
    /// - `config`: Configuration describing partition progression and inversion behavior.
    ///
    /// # Returns
    /// - `Result<BitflowEngine, BitflowError>`: Constructed engine or validation error.
    ///
    /// # Expected Output
    /// - Returns a configured engine; no stdout/stderr output.
    pub fn new(config: BitflowConfig) -> Result<Self, BitflowError> {
        validate_config(&config)?;
        let rng = StdRng::seed_from_u64(config.seed);
        Ok(Self { config, rng })
    }

    /// Returns a reference to the configuration.
    ///
    /// # Parameters
    /// - None.
    ///
    /// # Returns
    /// - `&BitflowConfig`: Configuration reference.
    ///
    /// # Expected Output
    /// - Returns a reference; no side effects.
    pub fn config(&self) -> &BitflowConfig {
        &self.config
    }

    /// Builds the partition list for a given iteration.
    ///
    /// # Parameters
    /// - `iteration`: Zero-based iteration index.
    ///
    /// # Returns
    /// - `Result<Vec<BitPartition>, BitflowError>`: Partition list for the iteration.
    ///
    /// # Expected Output
    /// - Returns partitions; no stdout/stderr output.
    pub fn partitions_for_iteration(
        &self,
        iteration: usize,
    ) -> Result<Vec<BitPartition>, BitflowError> {
        let partition_size = partition_size_for_iteration(
            &self.config.progression,
            iteration,
            self.config.min_partition_size,
            self.config.max_partition_size,
            self.config.bit_width,
        )?;
        Ok(build_partitions(self.config.bit_width, partition_size))
    }

    /// Generates bitflow candidates from an input message.
    ///
    /// # Parameters
    /// - `message_bits`: Bit vector representing the speculative message output.
    ///
    /// # Returns
    /// - `Result<Vec<BitflowCandidate>, BitflowError>`: Candidate list with metadata.
    ///
    /// # Expected Output
    /// - Returns generated candidates; no stdout/stderr output.
    pub fn generate_candidates(
        &mut self,
        message_bits: &[bool],
    ) -> Result<Vec<BitflowCandidate>, BitflowError> {
        if message_bits.len() != self.config.bit_width {
            return Err(BitflowError::MessageBitWidthMismatch);
        }
        let mut candidates = Vec::new();
        for iteration in 0..self.config.max_iterations {
            let partition_size = partition_size_for_iteration(
                &self.config.progression,
                iteration,
                self.config.min_partition_size,
                self.config.max_partition_size,
                self.config.bit_width,
            )?;
            let partitions = build_partitions(self.config.bit_width, partition_size);
            if partitions.is_empty() {
                continue;
            }
            let flip_limit = self.config.max_partitions_to_flip.min(partitions.len());
            let pow_mod_value = mod_pow(
                self.config.pow_mod_base,
                (iteration as u64).saturating_add(1),
                self.config.pow_mod_modulus,
            );
            for trial in 0..self.config.per_candidate_trials {
                let mut indices: Vec<usize> = (0..partitions.len()).collect();
                indices.shuffle(&mut self.rng);
                let flip_count = 1 + ((pow_mod_value + trial as u64) % flip_limit as u64) as usize;
                let mut inverted_partitions: Vec<usize> =
                    indices.into_iter().take(flip_count).collect();
                inverted_partitions.sort_unstable();
                let bits =
                    apply_partition_inversions(message_bits, &partitions, &inverted_partitions);
                candidates.push(BitflowCandidate {
                    iteration,
                    trial,
                    partition_size,
                    inverted_partitions,
                    bits,
                });
            }
        }
        Ok(candidates)
    }
}

/// Validates bitflow configuration values.
///
/// # Parameters
/// - `config`: Configuration to validate.
///
/// # Returns
/// - `Result<(), BitflowError>`: `Ok(())` on success.
///
/// # Expected Output
/// - Returns validation status; no stdout/stderr output.
fn validate_config(config: &BitflowConfig) -> Result<(), BitflowError> {
    if config.bit_width == 0 {
        return Err(BitflowError::InvalidBitWidth);
    }
    if config.min_partition_size == 0
        || config.max_partition_size == 0
        || config.min_partition_size > config.max_partition_size
        || config.max_partition_size > config.bit_width
    {
        return Err(BitflowError::InvalidPartitionRange);
    }
    if config.max_iterations == 0 {
        return Err(BitflowError::InvalidIterations);
    }
    if config.per_candidate_trials == 0 {
        return Err(BitflowError::InvalidTrials);
    }
    if config.max_partitions_to_flip == 0 {
        return Err(BitflowError::InvalidFlipCount);
    }
    if config.pow_mod_modulus == 0 {
        return Err(BitflowError::InvalidPowModulus);
    }
    validate_progression(&config.progression, config.bit_width)?;
    Ok(())
}

/// Validates partition progression settings.
///
/// # Parameters
/// - `progression`: Partition progression to validate.
/// - `bit_width`: Bit width used to cap partition sizes.
///
/// # Returns
/// - `Result<(), BitflowError>`: `Ok(())` on success.
///
/// # Expected Output
/// - Returns validation status; no stdout/stderr output.
fn validate_progression(
    progression: &PartitionProgression,
    bit_width: usize,
) -> Result<(), BitflowError> {
    match progression {
        PartitionProgression::Fixed { size } => {
            if *size == 0 || *size > bit_width {
                return Err(BitflowError::InvalidPartitionRange);
            }
        }
        PartitionProgression::Linear { start, step: _ } => {
            if *start == 0 || *start > bit_width {
                return Err(BitflowError::InvalidPartitionRange);
            }
        }
        PartitionProgression::Geometric { start, factor } => {
            if *start == 0 || *start > bit_width || *factor == 0 {
                return Err(BitflowError::InvalidPartitionRange);
            }
        }
        PartitionProgression::Sequence { sizes } => {
            if sizes.is_empty() || sizes.iter().any(|size| *size == 0 || *size > bit_width) {
                return Err(BitflowError::InvalidPartitionRange);
            }
        }
    }
    Ok(())
}

/// Computes the partition size for a given iteration.
///
/// # Parameters
/// - `progression`: Partition size progression model.
/// - `iteration`: Zero-based iteration index.
/// - `min_size`: Minimum allowable partition size.
/// - `max_size`: Maximum allowable partition size.
/// - `bit_width`: Bit width used as a ceiling.
///
/// # Returns
/// - `Result<usize, BitflowError>`: Partition size for the iteration.
///
/// # Expected Output
/// - Returns the partition size; no stdout/stderr output.
fn partition_size_for_iteration(
    progression: &PartitionProgression,
    iteration: usize,
    min_size: usize,
    max_size: usize,
    bit_width: usize,
) -> Result<usize, BitflowError> {
    let raw_size = match progression {
        PartitionProgression::Fixed { size } => *size,
        PartitionProgression::Linear { start, step } => {
            start.saturating_add(step.saturating_mul(iteration))
        }
        PartitionProgression::Geometric { start, factor } => {
            let mut size = *start;
            for _ in 0..iteration {
                size = size.saturating_mul(*factor);
            }
            size
        }
        PartitionProgression::Sequence { sizes } => sizes[iteration % sizes.len()],
    };
    let clamped = raw_size.clamp(min_size, max_size).min(bit_width);
    if clamped == 0 {
        return Err(BitflowError::InvalidPartitionRange);
    }
    Ok(clamped)
}

/// Builds contiguous partitions of a bit vector.
///
/// # Parameters
/// - `bit_width`: Total number of bits.
/// - `partition_size`: Requested size for each partition.
///
/// # Returns
/// - `Vec<BitPartition>`: Contiguous partitions covering the bit width.
///
/// # Expected Output
/// - Returns partitions; no stdout/stderr output.
fn build_partitions(bit_width: usize, partition_size: usize) -> Vec<BitPartition> {
    WindowPartitionSet::build(bit_width)
        .min_width(partition_size)
        .max_width(partition_size)
        .disallow_overlap()
        .contiguous()
        .generate()
        .expect("validated bitflow partition size should produce contiguous windows")
        .partitions()
        .iter()
        .map(|partition| BitPartition {
            start: partition.index(),
            end: partition.end_exclusive(),
        })
        .collect()
}

/// Applies partition-level inversions to a bit vector.
///
/// # Parameters
/// - `message_bits`: Input bit slice to transform.
/// - `partitions`: Partition list describing segment boundaries.
/// - `inverted_partitions`: Partition indices to invert.
///
/// # Returns
/// - `Vec<bool>`: New bit vector with specified partitions inverted.
///
/// # Expected Output
/// - Returns a transformed bit vector; no stdout/stderr output.
fn apply_partition_inversions(
    message_bits: &[bool],
    partitions: &[BitPartition],
    inverted_partitions: &[usize],
) -> Vec<bool> {
    let mut output = message_bits.to_vec();
    for &partition_idx in inverted_partitions {
        if let Some(partition) = partitions.get(partition_idx) {
            for bit in &mut output[partition.start..partition.end] {
                *bit = !*bit;
            }
        }
    }
    output
}

/// Computes modular exponentiation for scheduling values.
///
/// # Parameters
/// - `base`: Base value `c`.
/// - `exponent`: Exponent `x`.
/// - `modulus`: Modulus `N`.
///
/// # Returns
/// - `u64`: `base^exponent mod modulus`.
///
/// # Expected Output
/// - Returns the modular exponentiation result; no stdout/stderr output.
fn mod_pow(base: u64, exponent: u64, modulus: u64) -> u64 {
    let mut result = 1u64 % modulus;
    let mut base_acc = base % modulus;
    let mut exp = exponent;
    while exp > 0 {
        if exp & 1 == 1 {
            result = result.saturating_mul(base_acc) % modulus;
        }
        exp >>= 1;
        base_acc = base_acc.saturating_mul(base_acc) % modulus;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::avalanche::{AvalancheNode, search_avalanche_tree};

    fn bits_from_str(bits: &str) -> Vec<bool> {
        bits.chars().map(|c| c == '1').collect()
    }

    fn bits_to_string(bits: &[bool]) -> String {
        bits.iter()
            .map(|bit| if *bit { '1' } else { '0' })
            .collect()
    }

    fn accuracy_pct(candidate: &[bool], target: &[bool]) -> f64 {
        let matches = candidate
            .iter()
            .zip(target.iter())
            .filter(|(a, b)| a == b)
            .count();
        100.0 * matches as f64 / target.len() as f64
    }

    fn avalanche_reduce(candidates: &[Vec<bool>]) -> Vec<bool> {
        let nodes: Vec<AvalancheNode> = candidates
            .iter()
            .map(|bits| AvalancheNode {
                biases: vec![0.0; bits.len()],
                message_bits: bits.clone(),
            })
            .collect();
        search_avalanche_tree(nodes)
            .expect("avalanche search should succeed")
            .message_bits
    }

    #[test]
    fn test_bitflow_linear_progression_expected_candidates() {
        let config = BitflowConfig {
            bit_width: 8,
            min_partition_size: 2,
            max_partition_size: 4,
            progression: PartitionProgression::Linear { start: 2, step: 1 },
            max_iterations: 2,
            max_partitions_to_flip: 2,
            per_candidate_trials: 2,
            seed: 7,
            pow_mod_base: 5,
            pow_mod_modulus: 7,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let message = bits_from_str("11001100");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let candidate_bits: Vec<String> = candidates
            .iter()
            .map(|cand| bits_to_string(&cand.bits))
            .collect();
        let expected = vec!["11110000", "00001100", "11001111", "00101111"];
        assert_eq!(candidate_bits, expected);
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(bits_to_string(&avalanche_bits), "00000000");
    }

    #[test]
    fn test_bitflow_geometric_progression_expected_candidates() {
        let config = BitflowConfig {
            bit_width: 10,
            min_partition_size: 2,
            max_partition_size: 5,
            progression: PartitionProgression::Geometric {
                start: 2,
                factor: 2,
            },
            max_iterations: 2,
            max_partitions_to_flip: 2,
            per_candidate_trials: 2,
            seed: 11,
            pow_mod_base: 3,
            pow_mod_modulus: 11,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let message = bits_from_str("1010101010");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let candidate_bits: Vec<String> = candidates
            .iter()
            .map(|cand| bits_to_string(&cand.bits))
            .collect();
        let expected = vec!["0110011010", "0110101010", "0101010110", "1010010110"];
        assert_eq!(candidate_bits, expected);
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(bits_to_string(&avalanche_bits), "0000000010");
    }

    #[test]
    fn test_bitflow_sequence_progression_expected_candidates() {
        let config = BitflowConfig {
            bit_width: 9,
            min_partition_size: 2,
            max_partition_size: 4,
            progression: PartitionProgression::Sequence {
                sizes: vec![2, 3, 4],
            },
            max_iterations: 3,
            max_partitions_to_flip: 2,
            per_candidate_trials: 1,
            seed: 13,
            pow_mod_base: 7,
            pow_mod_modulus: 9,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let message = bits_from_str("111000111");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let candidate_bits: Vec<String> = candidates
            .iter()
            .map(|cand| bits_to_string(&cand.bits))
            .collect();
        let expected = vec!["111011110", "000000111", "111011000"];
        assert_eq!(candidate_bits, expected);
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(bits_to_string(&avalanche_bits), "000000000");
    }

    #[test]
    fn test_bitflow_pow_mod_flip_counts() {
        let config = BitflowConfig {
            bit_width: 12,
            min_partition_size: 3,
            max_partition_size: 3,
            progression: PartitionProgression::Fixed { size: 3 },
            max_iterations: 3,
            max_partitions_to_flip: 3,
            per_candidate_trials: 2,
            seed: 19,
            pow_mod_base: 5,
            pow_mod_modulus: 13,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let message = bits_from_str("101100111000");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let flip_counts: Vec<usize> = candidates
            .iter()
            .map(|cand| cand.inverted_partitions.len())
            .collect();
        let expected = vec![3, 1, 1, 2, 3, 1];
        assert_eq!(flip_counts, expected);
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(bits_to_string(&avalanche_bits), "000000000000");
    }

    #[test]
    fn test_bitflow_accuracy_improves_over_baseline() {
        let config = BitflowConfig {
            bit_width: 16,
            min_partition_size: 4,
            max_partition_size: 4,
            progression: PartitionProgression::Fixed { size: 4 },
            max_iterations: 3,
            max_partitions_to_flip: 2,
            per_candidate_trials: 3,
            seed: 23,
            pow_mod_base: 3,
            pow_mod_modulus: 7,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let target = bits_from_str("1111000011110000");
        let message = bits_from_str("1111000000001111");
        let baseline_accuracy = accuracy_pct(&message, &target);
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        let avalanche_accuracy = accuracy_pct(&avalanche_bits, &target);
        let best_accuracy = candidates
            .iter()
            .map(|cand| accuracy_pct(&cand.bits, &target))
            .fold(0.0_f64, f64::max);
        assert!(best_accuracy > baseline_accuracy);
        assert!(best_accuracy >= 75.0);
        assert!(avalanche_accuracy >= baseline_accuracy);
    }

    #[test]
    fn test_bitflow_iteration_limit_respected() {
        let config = BitflowConfig {
            bit_width: 10,
            min_partition_size: 2,
            max_partition_size: 4,
            progression: PartitionProgression::Linear { start: 2, step: 1 },
            max_iterations: 4,
            max_partitions_to_flip: 2,
            per_candidate_trials: 2,
            seed: 29,
            pow_mod_base: 2,
            pow_mod_modulus: 5,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let message = bits_from_str("1100110011");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        assert_eq!(candidates.len(), 8);
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(avalanche_bits.len(), 10);
    }

    #[test]
    fn test_bitflow_deterministic_seed_replay() {
        let config = BitflowConfig {
            bit_width: 8,
            min_partition_size: 2,
            max_partition_size: 4,
            progression: PartitionProgression::Sequence { sizes: vec![2, 4] },
            max_iterations: 2,
            max_partitions_to_flip: 2,
            per_candidate_trials: 2,
            seed: 31,
            pow_mod_base: 3,
            pow_mod_modulus: 7,
        };
        let message = bits_from_str("01010101");
        let mut engine_a = BitflowEngine::new(config.clone()).expect("valid config");
        let mut engine_b = BitflowEngine::new(config).expect("valid config");
        let candidates_a = engine_a.generate_candidates(&message).expect("candidates");
        let candidates_b = engine_b.generate_candidates(&message).expect("candidates");
        assert_eq!(candidates_a, candidates_b);
        let avalanche_bits = avalanche_reduce(
            &candidates_a
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        assert_eq!(bits_to_string(&avalanche_bits), "00000000");
    }

    #[test]
    fn test_bitflow_partitions_for_iteration_match_contiguous_window_layout() {
        let config = BitflowConfig {
            bit_width: 10,
            min_partition_size: 4,
            max_partition_size: 4,
            progression: PartitionProgression::Fixed { size: 4 },
            max_iterations: 1,
            max_partitions_to_flip: 2,
            per_candidate_trials: 1,
            seed: 43,
            pow_mod_base: 3,
            pow_mod_modulus: 7,
        };
        let engine = BitflowEngine::new(config).expect("valid config");

        let partitions = engine
            .partitions_for_iteration(0)
            .expect("partitions should build");

        assert_eq!(
            partitions,
            vec![
                BitPartition { start: 0, end: 4 },
                BitPartition { start: 4, end: 8 },
                BitPartition { start: 8, end: 10 },
            ]
        );
    }

    #[test]
    fn test_bitflow_high_accuracy_target_match() {
        let config = BitflowConfig {
            bit_width: 12,
            min_partition_size: 3,
            max_partition_size: 3,
            progression: PartitionProgression::Fixed { size: 3 },
            max_iterations: 1,
            max_partitions_to_flip: 4,
            per_candidate_trials: 4,
            seed: 37,
            pow_mod_base: 5,
            pow_mod_modulus: 11,
        };
        let mut engine = BitflowEngine::new(config).expect("valid config");
        let target = bits_from_str("000000000000");
        let message = bits_from_str("111111111111");
        let candidates = engine.generate_candidates(&message).expect("candidates");
        let avalanche_bits = avalanche_reduce(
            &candidates
                .iter()
                .map(|c| c.bits.clone())
                .collect::<Vec<_>>(),
        );
        let avalanche_accuracy = accuracy_pct(&avalanche_bits, &target);
        let best_accuracy = candidates
            .iter()
            .map(|cand| accuracy_pct(&cand.bits, &target))
            .fold(0.0_f64, f64::max);
        let candidate_matches_target = candidates.iter().any(|cand| cand.bits == target);
        assert!(best_accuracy >= 100.0);
        assert!(candidate_matches_target);
        assert!(avalanche_accuracy >= 100.0);
    }
}
